apiVersion: k3d.io/v1alpha2
kind: Simple
name: swiftkube
image: docker.io/rancher/k3s:v1.24.8-k3s1
servers: 1
agents: 2
options:
  k3d:
    wait: true
    timeout: "120s"
    disableLoadbalancer: true
  k3s:
    extraServerArgs:
      - --no-deploy=traefik,servicelb,metrics-server
